# GetSignatureMode example messages
# required as mandatory elements: MandantId, ClientSystemId, WorkplaceId
# Optional element (but required for session info): CardHandle to address (only eHBA supported) and userId
# If the userId is missing / wrong and comfort sig active: Exception (card has elevated security level with other userId)
### GetSignatureMode Example
WEBSOCKET ws://{{baseURL}}/websocket
Content-Type: application/json

{
    "type": "GetSignatureMode",
    "id": "{{$random.uuid}}",
    "runtimeConfig": {
        "eHBAHandle": "{{eHBAHandle}}",
        "SMCBHandle": "{{SMCBHandle}}",
        "connector.user-id": "{{userId}}",
        "connector.base-url": "{{connector.base-url}}",
        "connector.client-certificate": "{{connector.client-certificate}}",
        "connector.client-certificate-password": "{{connector.client-certificate-password}}",
        "connector.client-system-id": "{{connector.client-system-id}}",
        "connector.mandant-id": "{{connector.mandant-id}}",
        "connector.workplace-id": "{{connector.workplace-id}}",
        "connector.version": "{{connector.version}}",
        "connector.basic-auth-username": null,
        "connector.basic-auth-password": null
    }
}
