WEBSOCKET ws://{{baseURL}}/websocket
Content-Type: application/json // Content highlighting only

{
  "type": "SignAndUploadBundles",
  "runtimeConfig": {
        "eHBAHandle": "{{eHBAHandle}}",
        "SMCBHandle": "{{SMCBHandle}}",
        "connector.user-id": "{{userId}}",
        "connector.base-url": "{{connector.base-url}}",
        "connector.client-certificate": "{{connector.client-certificate}}",
        "connector.client-certificate-password": "{{connector.client-certificate-password}}",
        "connector.client-system-id": "{{connector.client-system-id}}",
        "connector.mandant-id": "{{connector.mandant-id}}",
        "connector.workplace-id": "{{connector.workplace-id}}",
        "connector.version": "{{connector.version}}",
        "connector.basic-auth-username": null,
        "connector.basic-auth-password": null
        },
  "payload": [
    [{
  "type": "document",
  "entry": [
    {
      "fullUrl": "http://pvs.praxis.local/fhir/Composition/b0aa06fb-e3d0-4821-a982-6a8c9219ae8c",
      "resource": {
        "date": "2024-04-12T09:50:00Z",
        "status": "final",
        "custodian": {
          "reference": "Organization/d9984508-b7d7-4e1b-bf27-90b77056953a"
        },
        "subject": {
          "reference": "Patient/aeb776c7-4525-4e73-be2d-2523f21fdbbf"
        },
        "extension": [
          {
            "valueCoding": {
              "code": "00",
              "system": "https://fhir.kbv.de/CodeSystem/KBV_CS_SFHIR_KBV_STATUSKENNZEICHEN"
            },
            "url": "https://fhir.kbv.de/StructureDefinition/KBV_EX_FOR_Legal_basis"
          }
        ],
        "type": {
          "coding": [
            {
              "code": "e16A",
              "system": "https://fhir.kbv.de/CodeSystem/KBV_CS_SFHIR_KBV_FORMULAR_ART"
            }
          ]
        },
        "section": [
          {
            "entry": [
              {
                "reference": "MedicationRequest/7610cb0f-5c2c-432d-aa49-1d5ee33294c9"
              }
            ],
            "code": {
              "coding": [
                {
                  "code": "Prescription",
                  "system": "https://fhir.kbv.de/CodeSystem/KBV_CS_ERP_Section_Type"
                }
              ]
            }
          },
          {
            "entry": [
              {
                "reference": "Coverage/03896e8e-aaff-4761-a328-4f15246d6304"
              }
            ],
            "code": {
              "coding": [
                {
                  "code": "Coverage",
                  "system": "https://fhir.kbv.de/CodeSystem/KBV_CS_ERP_Section_Type"
                }
              ]
            }
          }
        ],
        "meta": {
          "profile": [
            "https://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Composition|1.1.0"
          ]
        },
        "author": [
          {
            "reference": "Practitioner/bdb1c784-70a4-4f08-85c6-2d176da70f78",
            "type": "Practitioner"
          },
          {
            "identifier": {
              "value": "Y/400/2107/36/999",
              "system": "https://fhir.kbv.de/NamingSystem/KBV_NS_FOR_Pruefnummer"
            },
            "type": "Device"
          }
        ],
        "title": "elektronische Arzneimittelverordnung",
        "resourceType": "Composition",
        "id": "b0aa06fb-e3d0-4821-a982-6a8c9219ae8c"
      }
    },
    {
      "fullUrl": "http://pvs.praxis.local/fhir/Coverage/03896e8e-aaff-4761-a328-4f15246d6304",
      "resource": {
        "extension": [
          {
            "valueCoding": {
              "code": "00",
              "system": "https://fhir.kbv.de/CodeSystem/KBV_CS_SFHIR_KBV_PERSONENGRUPPE"
            },
            "url": "http://fhir.de/StructureDefinition/gkv/besondere-personengruppe"
          },
          {
            "valueCoding": {
              "code": "00",
              "system": "https://fhir.kbv.de/CodeSystem/KBV_CS_SFHIR_KBV_DMP"
            },
            "url": "http://fhir.de/StructureDefinition/gkv/dmp-kennzeichen"
          },
          {
            "valueCoding": {
              "code": "5",
              "system": "https://fhir.kbv.de/CodeSystem/KBV_CS_SFHIR_KBV_VERSICHERTENSTATUS"
            },
            "url": "http://fhir.de/StructureDefinition/gkv/versichertenart"
          }
        ],
        "type": {
          "coding": [
            {
              "code": "GKV",
              "system": "http://fhir.de/CodeSystem/versicherungsart-de-basis"
            }
          ]
        },
        "payor": [
          {
            "display": "Techniker Krankenkasse",
            "identifier": {
              "value": "101575519",
              "system": "http://fhir.de/sid/arge-ik/iknr"
            }
          }
        ],
        "resourceType": "Coverage",
        "beneficiary": {
          "reference": "Patient/aeb776c7-4525-4e73-be2d-2523f21fdbbf"
        },
        "status": "active",
        "meta": {
          "profile": [
            "https://fhir.kbv.de/StructureDefinition/KBV_PR_FOR_Coverage|1.1.0"
          ]
        },
        "id": "03896e8e-aaff-4761-a328-4f15246d6304"
      }
    },
    {
      "fullUrl": "http://pvs.praxis.local/fhir/Patient/aeb776c7-4525-4e73-be2d-2523f21fdbbf",
      "resource": {
        "birthDate": "1982-01-01",
        "name": [
          {
            "_family": {
              "extension": [
                {
                  "valueString": "Mustermann",
                  "url": "http://hl7.org/fhir/StructureDefinition/humanname-own-name"
                }
              ]
            },
            "given": [
              "Juliane"
            ],
            "use": "official",
            "family": "Mustermann"
          }
        ],
        "resourceType": "Patient",
        "address": [
          {
            "postalCode": "64289",
            "type": "both",
            "_line": [
              {
                "extension": [
                  {
                    "valueString": "Schottener Weg",
                    "url": "http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-streetName"
                  },
                  {
                    "valueString": "5",
                    "url": "http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-houseNumber"
                  }
                ]
              }
            ],
            "city": "Darmstadt",
            "country": "D",
            "line": [
              "Schottener Weg 5"
            ]
          }
        ],
        "identifier": [
          {
            "type": {
              "coding": [
                {
                  "code": "GKV",
                  "system": "http://fhir.de/CodeSystem/identifier-type-de-basis"
                }
              ]
            },
            "value": "T027875325",
            "system": "http://fhir.de/sid/gkv/kvid-10"
          }
        ],
        "meta": {
          "profile": [
            "https://fhir.kbv.de/StructureDefinition/KBV_PR_FOR_Patient|1.1.0"
          ]
        },
        "id": "aeb776c7-4525-4e73-be2d-2523f21fdbbf"
      }
    },
    {
      "fullUrl": "http://pvs.praxis.local/fhir/Practitioner/bdb1c784-70a4-4f08-85c6-2d176da70f78",
      "resource": {
        "qualification": [
          {
            "code": {
              "coding": [
                {
                  "code": "00",
                  "system": "https://fhir.kbv.de/CodeSystem/KBV_CS_FOR_Qualification_Type"
                }
              ]
            }
          },
          {
            "code": {
              "coding": [
                {
                  "code": "Berufsbezeichnung",
                  "system": "https://fhir.kbv.de/CodeSystem/KBV_CS_FOR_Berufsbezeichnung"
                }
              ],
              "text": "Arzt"
            }
          }
        ],
        "name": [
          {
            "_family": {
              "extension": [
                {
                  "valueString": "Bëírliner",
                  "url": "http://hl7.org/fhir/StructureDefinition/humanname-own-name"
                }
              ]
            },
            "given": [
              "Maria"
            ],
            "use": "official",
            "family": "Bëírliner"
          }
        ],
        "resourceType": "Practitioner",
        "identifier": [
          {
            "type": {
              "coding": [
                {
                  "code": "LANR",
                  "system": "http://terminology.hl7.org/CodeSystem/v2-0203"
                }
              ]
            },
            "value": "123456499",
            "system": "https://fhir.kbv.de/NamingSystem/KBV_NS_Base_ANR"
          }
        ],
        "meta": {
          "profile": [
            "https://fhir.kbv.de/StructureDefinition/KBV_PR_FOR_Practitioner|1.1.0"
          ]
        },
        "id": "bdb1c784-70a4-4f08-85c6-2d176da70f78"
      }
    },
    {
      "fullUrl": "http://pvs.praxis.local/fhir/Organization/d9984508-b7d7-4e1b-bf27-90b77056953a",
      "resource": {
        "telecom": [
          {
            "value": "0123456789",
            "system": "phone"
          }
        ],
        "name": "Praxis SigmuntowskíTEST-ONLY",
        "resourceType": "Organization",
        "address": [
          {
            "postalCode": "93055",
            "type": "both",
            "_line": [
              {
                "extension": [
                  {
                    "valueString": "Sulzfeldstraße",
                    "url": "http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-streetName"
                  },
                  {
                    "valueString": "7",
                    "url": "http://hl7.org/fhir/StructureDefinition/iso21090-ADXP-houseNumber"
                  }
                ]
              }
            ],
            "city": "Regensburg",
            "country": "D",
            "line": [
              "Sulzfeldstraße 7"
            ]
          }
        ],
        "identifier": [
          {
            "type": {
              "coding": [
                {
                  "code": "BSNR",
                  "system": "http://terminology.hl7.org/CodeSystem/v2-0203"
                }
              ]
            },
            "value": "036812345",
            "system": "https://fhir.kbv.de/NamingSystem/KBV_NS_Base_BSNR"
          }
        ],
        "meta": {
          "profile": [
            "https://fhir.kbv.de/StructureDefinition/KBV_PR_FOR_Organization|1.1.0"
          ]
        },
        "id": "d9984508-b7d7-4e1b-bf27-90b77056953a"
      }
    },
    {
      "fullUrl": "http://pvs.praxis.local/fhir/MedicationRequest/7610cb0f-5c2c-432d-aa49-1d5ee33294c9",
      "resource": {
        "medicationReference": {
          "reference": "Medication/2f419f04-20f8-49b6-985e-f7b82f1bfd14"
        },
        "insurance": [
          {
            "reference": "Coverage/03896e8e-aaff-4761-a328-4f15246d6304"
          }
        ],
        "status": "active",
        "substitution": {
          "allowedBoolean": true
        },
        "requester": {
          "reference": "Practitioner/bdb1c784-70a4-4f08-85c6-2d176da70f78"
        },
        "authoredOn": "2024-04-12",
        "subject": {
          "reference": "Patient/aeb776c7-4525-4e73-be2d-2523f21fdbbf"
        },
        "extension": [
          {
            "valueCoding": {
              "code": "1",
              "system": "https://fhir.kbv.de/CodeSystem/KBV_CS_FOR_StatusCoPayment"
            },
            "url": "https://fhir.kbv.de/StructureDefinition/KBV_EX_FOR_StatusCoPayment"
          },
          {
            "valueBoolean": false,
            "url": "https://fhir.kbv.de/StructureDefinition/KBV_EX_ERP_EmergencyServicesFee"
          },
          {
            "valueBoolean": false,
            "url": "https://fhir.kbv.de/StructureDefinition/KBV_EX_ERP_BVG"
          },
          {
            "extension": [
              {
                "valueBoolean": false,
                "url": "Kennzeichen"
              }
            ],
            "url": "https://fhir.kbv.de/StructureDefinition/KBV_EX_ERP_Multiple_Prescription"
          }
        ],
        "dispenseRequest": {
          "quantity": {
            "code": "{Package}",
            "system": "http://unitsofmeasure.org",
            "value": 1
          }
        },
        "meta": {
          "profile": [
            "https://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Prescription|1.1.0"
          ]
        },
        "intent": "order",
        "dosageInstruction": [
          {
            "extension": [
              {
                "valueBoolean": false,
                "url": "https://fhir.kbv.de/StructureDefinition/KBV_EX_ERP_DosageFlag"
              }
            ]
          }
        ],
        "resourceType": "MedicationRequest",
        "id": "7610cb0f-5c2c-432d-aa49-1d5ee33294c9"
      }
    },
    {
      "fullUrl": "http://pvs.praxis.local/fhir/Medication/2f419f04-20f8-49b6-985e-f7b82f1bfd14",
      "resource": {
        "extension": [
          {
            "valueCoding": {
              "code": "00",
              "system": "https://fhir.kbv.de/CodeSystem/KBV_CS_ERP_Medication_Category"
            },
            "url": "https://fhir.kbv.de/StructureDefinition/KBV_EX_ERP_Medication_Category"
          },
          {
            "valueBoolean": false,
            "url": "https://fhir.kbv.de/StructureDefinition/KBV_EX_ERP_Medication_Vaccine"
          }
        ],
        "code": {
          "coding": [
            {
              "code": "freitext",
              "system": "https://fhir.kbv.de/CodeSystem/KBV_CS_ERP_Medication_Type"
            }
          ],
          "text": "Isopto Max ATR"
        },
        "resourceType": "Medication",
        "meta": {
          "profile": [
            "https://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Medication_FreeText|1.1.0"
          ]
        },
        "id": "2f419f04-20f8-49b6-985e-f7b82f1bfd14"
      }
    }
  ],
  "resourceType": "Bundle",
  "timestamp": "2024-04-12T09:50:00Z",
  "identifier": {
    "value": "160.100.000.000.006.24",
    "system": "https://gematik.de/fhir/erp/NamingSystem/GEM_ERP_NS_PrescriptionId"
  },
  "meta": {
    "profile": [
      "https://fhir.kbv.de/StructureDefinition/KBV_PR_ERP_Bundle|1.1.0"
    ]
  },
  "id": "b8b68c8e-9ae8-41ee-832d-5d91666dd5f5"
}]
  ]
}