package health.ere.ps.service.muster16.parser.rgxer.model;

public enum Muster16Field {
    INSURANCE_COMPANY,
    INSURANCE_COMPANY_ID,
    PATIENT_NAME_PREFIX,
    PATIENT_FIRST_NAME,
    PATIENT_LAST_NAME,
    PATIENT_STREET_NAME,
    PATIENT_STREET_NUMBER,
    PATIENT_CITY,
    PATIENT_ZIPCODE,
    PATIENT_DATE_OF_BIRTH,
    CLINIC_ID,
    DOCTOR_ID,
    PRESCRIPTION_DATE,
    PRESCRIPTION_LIST,
    PATIENT_INSURANCE_ID,
    IS_WITH_PAYMENT
}
